#server
server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    threads:
      max: 1000
      
#spring
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/dbms?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: root
  thymeleaf:
    cache: false
    prefix: classpath:/templates/pages/
    suffix: .html
  aop:
    proxy-target-class: false
  task:
   execution:
     pool:
       queue-capacity: 128
       core-size: 5
       max-size: 128
       keep-alive: 60000
     thread-name-prefix: db-service-task-
 

 
#mybatis
mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:/mapper/*/*.xml
 
#lOG
logging:
  level:
    com.cy: DEBUG