INSERT INTO `sys_user_roles`(`id`, `user_id`, `role_id`) VALUES (70, 18, 49);
INSERT INTO `sys_user_roles`(`id`, `user_id`, `role_id`) VALUES (71, 17, 48);
INSERT INTO `sys_user_roles`(`id`, `user_id`, `role_id`) VALUES (72, 16, 47);
INSERT INTO `sys_user_roles`(`id`, `user_id`, `role_id`) VALUES (75, 1, 47);
INSERT INTO `sys_user_roles`(`id`, `user_id`, `role_id`) VALUES (76, 19, 49);
INSERT INTO `sys_user_roles`(`id`, `user_id`, `role_id`) VALUES (77, 20, 47);
INSERT INTO `sys_user_roles`(`id`, `user_id`, `role_id`) VALUES (78, 20, 48);
INSERT INTO `sys_user_roles`(`id`, `user_id`, `role_id`) VALUES (80, 22, 48);
INSERT INTO `sys_user_roles`(`id`, `user_id`, `role_id`) VALUES (83, 23, 49);
